services:
  - type: web
    name: chat-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python chatbot.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
